/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author Iolanda
 */
public class MainFrame extends javax.swing.JFrame {

    private Map<String, JLabel> map;
    private ArrayList<Integer> sacco;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        setTitle("La Tombolata a Sorcio Aperto");
        sacco = initSacco();
        initComponents();
        setLocationRelativeTo(null);
        mapJLabels();
        setImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                Color light = new Color(220,240,255);
                Color dark = new Color(0, 40, 255);
                GradientPaint gp = new GradientPaint(0,0,light,getWidth(),0,dark);
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jPanel2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l27 = new javax.swing.JLabel();
        l28 = new javax.swing.JLabel();
        l29 = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        l30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        l31 = new javax.swing.JLabel();
        l32 = new javax.swing.JLabel();
        l33 = new javax.swing.JLabel();
        l34 = new javax.swing.JLabel();
        l35 = new javax.swing.JLabel();
        l45 = new javax.swing.JLabel();
        l41 = new javax.swing.JLabel();
        l42 = new javax.swing.JLabel();
        l43 = new javax.swing.JLabel();
        l44 = new javax.swing.JLabel();
        l52 = new javax.swing.JLabel();
        l53 = new javax.swing.JLabel();
        l54 = new javax.swing.JLabel();
        l51 = new javax.swing.JLabel();
        l55 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        l36 = new javax.swing.JLabel();
        l37 = new javax.swing.JLabel();
        l38 = new javax.swing.JLabel();
        l39 = new javax.swing.JLabel();
        l40 = new javax.swing.JLabel();
        l50 = new javax.swing.JLabel();
        l46 = new javax.swing.JLabel();
        l47 = new javax.swing.JLabel();
        l48 = new javax.swing.JLabel();
        l49 = new javax.swing.JLabel();
        l57 = new javax.swing.JLabel();
        l58 = new javax.swing.JLabel();
        l59 = new javax.swing.JLabel();
        l56 = new javax.swing.JLabel();
        l60 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        l61 = new javax.swing.JLabel();
        l62 = new javax.swing.JLabel();
        l63 = new javax.swing.JLabel();
        l64 = new javax.swing.JLabel();
        l65 = new javax.swing.JLabel();
        l75 = new javax.swing.JLabel();
        l71 = new javax.swing.JLabel();
        l72 = new javax.swing.JLabel();
        l73 = new javax.swing.JLabel();
        l74 = new javax.swing.JLabel();
        l82 = new javax.swing.JLabel();
        l83 = new javax.swing.JLabel();
        l84 = new javax.swing.JLabel();
        l81 = new javax.swing.JLabel();
        l85 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        l66 = new javax.swing.JLabel();
        l67 = new javax.swing.JLabel();
        l68 = new javax.swing.JLabel();
        l69 = new javax.swing.JLabel();
        l70 = new javax.swing.JLabel();
        l80 = new javax.swing.JLabel();
        l76 = new javax.swing.JLabel();
        l77 = new javax.swing.JLabel();
        l78 = new javax.swing.JLabel();
        l79 = new javax.swing.JLabel();
        l87 = new javax.swing.JLabel();
        l88 = new javax.swing.JLabel();
        l89 = new javax.swing.JLabel();
        l86 = new javax.swing.JLabel();
        l90 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        l1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 0, 0));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("1");
        l1.setBorder(new CircleBorder(2, new Color(50, 50, 50)));
        l1.setName("l1"); // NOI18N

        l2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 0, 0));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("2");
        l2.setBorder(new CircleBorder(2, new Color(50, 50, 50)));
        l2.setName("l2"); // NOI18N

        l3.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 0, 0));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("3");
        l3.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 0, 0));
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setText("4");
        l4.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l5.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 0, 0));
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setText("5");
        l5.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l15.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l15.setForeground(new java.awt.Color(255, 0, 0));
        l15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l15.setText("15");
        l15.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l11.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l11.setForeground(new java.awt.Color(255, 0, 0));
        l11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l11.setText("11");
        l11.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l12.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l12.setForeground(new java.awt.Color(255, 0, 0));
        l12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l12.setText("12");
        l12.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l13.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l13.setForeground(new java.awt.Color(255, 0, 0));
        l13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l13.setText("13");
        l13.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l14.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l14.setForeground(new java.awt.Color(255, 0, 0));
        l14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l14.setText("14");
        l14.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l22.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l22.setForeground(new java.awt.Color(255, 0, 0));
        l22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l22.setText("22");
        l22.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l23.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l23.setForeground(new java.awt.Color(255, 0, 0));
        l23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l23.setText("23");
        l23.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l24.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l24.setForeground(new java.awt.Color(255, 0, 0));
        l24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l24.setText("24");
        l24.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l21.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l21.setForeground(new java.awt.Color(255, 0, 0));
        l21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l21.setText("21");
        l21.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l25.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l25.setForeground(new java.awt.Color(255, 0, 0));
        l25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l25.setText("25");
        l25.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        l6.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 0, 0));
        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l6.setText("6");
        l6.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l7.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l7.setForeground(new java.awt.Color(255, 0, 0));
        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l7.setText("7");
        l7.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l8.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l8.setForeground(new java.awt.Color(255, 0, 0));
        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8.setText("8");
        l8.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l9.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l9.setForeground(new java.awt.Color(255, 0, 0));
        l9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l9.setText("9");
        l9.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l10.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l10.setForeground(new java.awt.Color(255, 0, 0));
        l10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l10.setText("10");
        l10.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l20.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l20.setForeground(new java.awt.Color(255, 0, 0));
        l20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l20.setText("20");
        l20.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l16.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l16.setForeground(new java.awt.Color(255, 0, 0));
        l16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l16.setText("16");
        l16.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l17.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l17.setForeground(new java.awt.Color(255, 0, 0));
        l17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l17.setText("17");
        l17.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l18.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l18.setForeground(new java.awt.Color(255, 0, 0));
        l18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l18.setText("18");
        l18.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l19.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l19.setForeground(new java.awt.Color(255, 0, 0));
        l19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l19.setText("19");
        l19.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l27.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l27.setForeground(new java.awt.Color(255, 0, 0));
        l27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l27.setText("27");
        l27.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l28.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l28.setForeground(new java.awt.Color(255, 0, 0));
        l28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l28.setText("28");
        l28.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l29.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l29.setForeground(new java.awt.Color(255, 0, 0));
        l29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l29.setText("29");
        l29.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l26.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l26.setForeground(new java.awt.Color(255, 0, 0));
        l26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l26.setText("26");
        l26.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l30.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l30.setForeground(new java.awt.Color(255, 0, 0));
        l30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l30.setText("30");
        l30.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(l26, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l28, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l29, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l30, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l26, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l28, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l29, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l30, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        l31.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l31.setForeground(new java.awt.Color(255, 0, 0));
        l31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l31.setText("31");
        l31.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l32.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l32.setForeground(new java.awt.Color(255, 0, 0));
        l32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l32.setText("32");
        l32.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l33.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l33.setForeground(new java.awt.Color(255, 0, 0));
        l33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l33.setText("33");
        l33.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l34.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l34.setForeground(new java.awt.Color(255, 0, 0));
        l34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l34.setText("34");
        l34.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l35.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l35.setForeground(new java.awt.Color(255, 0, 0));
        l35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l35.setText("35");
        l35.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l45.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l45.setForeground(new java.awt.Color(255, 0, 0));
        l45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l45.setText("45");
        l45.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l41.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l41.setForeground(new java.awt.Color(255, 0, 0));
        l41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l41.setText("41");
        l41.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l42.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l42.setForeground(new java.awt.Color(255, 0, 0));
        l42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l42.setText("42");
        l42.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l43.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l43.setForeground(new java.awt.Color(255, 0, 0));
        l43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l43.setText("43");
        l43.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l44.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l44.setForeground(new java.awt.Color(255, 0, 0));
        l44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l44.setText("44");
        l44.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l52.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l52.setForeground(new java.awt.Color(255, 0, 0));
        l52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l52.setText("52");
        l52.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l53.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l53.setForeground(new java.awt.Color(255, 0, 0));
        l53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l53.setText("53");
        l53.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l54.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l54.setForeground(new java.awt.Color(255, 0, 0));
        l54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l54.setText("54");
        l54.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l51.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l51.setForeground(new java.awt.Color(255, 0, 0));
        l51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l51.setText("51");
        l51.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l55.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l55.setForeground(new java.awt.Color(255, 0, 0));
        l55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l55.setText("55");
        l55.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l31, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l32, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l33, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l34, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l35, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l41, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l42, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l43, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l44, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l45, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l51, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l52, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l53, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l54, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l55, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l31, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l32, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l33, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l34, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l35, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l41, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l42, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l43, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l44, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l45, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l51, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l52, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l53, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l54, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l55, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        l36.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l36.setForeground(new java.awt.Color(255, 0, 0));
        l36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l36.setText("36");
        l36.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l37.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l37.setForeground(new java.awt.Color(255, 0, 0));
        l37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l37.setText("37");
        l37.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l38.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l38.setForeground(new java.awt.Color(255, 0, 0));
        l38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l38.setText("38");
        l38.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l39.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l39.setForeground(new java.awt.Color(255, 0, 0));
        l39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l39.setText("39");
        l39.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l40.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l40.setForeground(new java.awt.Color(255, 0, 0));
        l40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l40.setText("40");
        l40.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l50.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l50.setForeground(new java.awt.Color(255, 0, 0));
        l50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l50.setText("50");
        l50.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l46.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l46.setForeground(new java.awt.Color(255, 0, 0));
        l46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l46.setText("46");
        l46.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l47.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l47.setForeground(new java.awt.Color(255, 0, 0));
        l47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l47.setText("47");
        l47.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l48.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l48.setForeground(new java.awt.Color(255, 0, 0));
        l48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l48.setText("48");
        l48.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l49.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l49.setForeground(new java.awt.Color(255, 0, 0));
        l49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l49.setText("49");
        l49.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l57.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l57.setForeground(new java.awt.Color(255, 0, 0));
        l57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l57.setText("57");
        l57.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l58.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l58.setForeground(new java.awt.Color(255, 0, 0));
        l58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l58.setText("58");
        l58.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l59.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l59.setForeground(new java.awt.Color(255, 0, 0));
        l59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l59.setText("59");
        l59.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l56.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l56.setForeground(new java.awt.Color(255, 0, 0));
        l56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l56.setText("56");
        l56.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l60.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l60.setForeground(new java.awt.Color(255, 0, 0));
        l60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l60.setText("60");
        l60.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(l36, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l37, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l38, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l39, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l40, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(l46, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l47, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l48, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l49, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l50, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(l56, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l57, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l58, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l59, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l60, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l36, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l37, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l38, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l39, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l40, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l46, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l47, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l48, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l49, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l50, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l56, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l57, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l58, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l59, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l60, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        l61.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l61.setForeground(new java.awt.Color(255, 0, 0));
        l61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l61.setText("61");
        l61.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l62.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l62.setForeground(new java.awt.Color(255, 0, 0));
        l62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l62.setText("62");
        l62.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l63.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l63.setForeground(new java.awt.Color(255, 0, 0));
        l63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l63.setText("63");
        l63.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l64.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l64.setForeground(new java.awt.Color(255, 0, 0));
        l64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l64.setText("64");
        l64.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l65.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l65.setForeground(new java.awt.Color(255, 0, 0));
        l65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l65.setText("65");
        l65.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l75.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l75.setForeground(new java.awt.Color(255, 0, 0));
        l75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l75.setText("75");
        l75.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l71.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l71.setForeground(new java.awt.Color(255, 0, 0));
        l71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l71.setText("71");
        l71.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l72.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l72.setForeground(new java.awt.Color(255, 0, 0));
        l72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l72.setText("72");
        l72.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l73.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l73.setForeground(new java.awt.Color(255, 0, 0));
        l73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l73.setText("73");
        l73.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l74.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l74.setForeground(new java.awt.Color(255, 0, 0));
        l74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l74.setText("74");
        l74.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l82.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l82.setForeground(new java.awt.Color(255, 0, 0));
        l82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l82.setText("82");
        l82.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l83.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l83.setForeground(new java.awt.Color(255, 0, 0));
        l83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l83.setText("83");
        l83.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l84.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l84.setForeground(new java.awt.Color(255, 0, 0));
        l84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l84.setText("84");
        l84.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l81.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l81.setForeground(new java.awt.Color(255, 0, 0));
        l81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l81.setText("81");
        l81.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l85.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l85.setForeground(new java.awt.Color(255, 0, 0));
        l85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l85.setText("85");
        l85.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(l61, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l62, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l63, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l64, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l65, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(l71, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l72, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l73, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l74, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l75, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(l81, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l82, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l83, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l84, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l85, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l61, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l62, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l63, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l64, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l65, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l71, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l72, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l73, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l74, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l75, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l81, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l82, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l83, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l84, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l85, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        l66.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l66.setForeground(new java.awt.Color(255, 0, 0));
        l66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l66.setText("66");
        l66.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l67.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l67.setForeground(new java.awt.Color(255, 0, 0));
        l67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l67.setText("67");
        l67.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l68.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l68.setForeground(new java.awt.Color(255, 0, 0));
        l68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l68.setText("68");
        l68.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l69.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l69.setForeground(new java.awt.Color(255, 0, 0));
        l69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l69.setText("69");
        l69.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l70.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l70.setForeground(new java.awt.Color(255, 0, 0));
        l70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l70.setText("70");
        l70.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l80.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l80.setForeground(new java.awt.Color(255, 0, 0));
        l80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l80.setText("80");
        l80.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l76.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l76.setForeground(new java.awt.Color(255, 0, 0));
        l76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l76.setText("76");
        l76.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l77.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l77.setForeground(new java.awt.Color(255, 0, 0));
        l77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l77.setText("77");
        l77.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l78.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l78.setForeground(new java.awt.Color(255, 0, 0));
        l78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l78.setText("78");
        l78.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l79.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l79.setForeground(new java.awt.Color(255, 0, 0));
        l79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l79.setText("79");
        l79.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l87.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l87.setForeground(new java.awt.Color(255, 0, 0));
        l87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l87.setText("87");
        l87.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l88.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l88.setForeground(new java.awt.Color(255, 0, 0));
        l88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l88.setText("88");
        l88.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l89.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l89.setForeground(new java.awt.Color(255, 0, 0));
        l89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l89.setText("89");
        l89.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l86.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l86.setForeground(new java.awt.Color(255, 0, 0));
        l86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l86.setText("86");
        l86.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        l90.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l90.setForeground(new java.awt.Color(255, 0, 0));
        l90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l90.setText("90");
        l90.setBorder(new CircleBorder(2, new Color(50, 50, 50)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(l66, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l67, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l68, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l69, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l70, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(l76, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l77, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l78, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l79, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l80, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(l86, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l87, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l88, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l89, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l90, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l66, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l67, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l68, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l69, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l70, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l76, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l77, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l78, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l79, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l80, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l86, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l87, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l88, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l89, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l90, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jList1.setModel(new DefaultListModel<String>());
        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cronologia Estrazioni"));
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Numero");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Estrai");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Giocate");

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jCheckBoxMenuItem1.setText("Ambo");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jCheckBoxMenuItem2.setText("Terno");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jCheckBoxMenuItem3.setText("Quaterna");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jCheckBoxMenuItem4.setText("Cinquina");
        jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem4);

        jCheckBoxMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jCheckBoxMenuItem5.setText("Tombola");
        jCheckBoxMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem5);

        jCheckBoxMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jCheckBoxMenuItem6.setText("Tombolina");
        jMenu2.add(jCheckBoxMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int numero = sacco.remove((int) (Math.random()*sacco.size()));
        new EstrattoDiag(this, true, ""+numero).setVisible(true);
        map.get("l"+(numero)).setForeground(new Color(0, 190, 0));
        ((DefaultListModel<String>)jList1.getModel()).addElement("Estratto: " + numero);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        switch(JOptionPane.showConfirmDialog(this, "Confermi la chiusura? La partita andrà persa.", "Conferma chiusura", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)) {
            case JOptionPane.YES_OPTION:
                System.exit(0);
            case JOptionPane.NO_OPTION:
                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                break;
        }
    }//GEN-LAST:event_formWindowClosing

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        jCheckBoxMenuItem1.setSelected(true);
        ((DefaultListModel<String>)jList1.getModel()).addElement("E' stato fatto AMBO - Cartella n. " 
                + JOptionPane.showInputDialog("Inserire Numero Cartella"));
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        jCheckBoxMenuItem2.setSelected(true);
        ((DefaultListModel<String>)jList1.getModel()).addElement("E' stato fatto TERNO - Cartella n. "
                + JOptionPane.showInputDialog("Inserire Numero Cartella"));
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        jCheckBoxMenuItem3.setSelected(true);
        ((DefaultListModel<String>)jList1.getModel()).addElement("E' stata fatta QUATERNA - Cartella n. "
                + JOptionPane.showInputDialog("Inserire Numero Cartella"));
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
        jCheckBoxMenuItem4.setSelected(true);
        ((DefaultListModel<String>)jList1.getModel()).addElement("E' stata fatta CINQUINA - Cartella n. "
                + JOptionPane.showInputDialog("Inserire Numero Cartella"));
    }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

    private void jCheckBoxMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem5ActionPerformed
        jCheckBoxMenuItem5.setSelected(true);
        ((DefaultListModel<String>)jList1.getModel()).addElement("E' stata fatta TOMBOLA! - Cartella n. "
                + JOptionPane.showInputDialog("Inserire Numero Cartella"));        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem5ActionPerformed

    private void mapJLabels() {
        map = new HashMap<>();
        map.put("l1", l1);
        map.put("l2", l2);
        map.put("l3", l3);
        map.put("l4", l4);
        map.put("l5", l5);
        map.put("l6", l6);
        map.put("l7", l7);
        map.put("l8", l8);
        map.put("l9", l9);
        map.put("l10",l10);
        map.put("l11",l11);
        map.put("l12",l12);
        map.put("l13",l13);
        map.put("l14",l14);
        map.put("l15",l15);
        map.put("l16", l16);
        map.put("l17", l17);
        map.put("l18", l18);
        map.put("l19", l19);
        map.put("l20", l20);
        map.put("l21", l21);
        map.put("l22", l22);
        map.put("l23", l23);
        map.put("l24", l24);
        map.put("l25", l25);
        map.put("l26", l26);
        map.put("l27", l27);
        map.put("l28", l28);
        map.put("l29", l29);
        map.put("l30", l30);
        map.put("l31", l31);
        map.put("l32", l32);
        map.put("l33", l33);
        map.put("l34", l35);
        map.put("l36", l36);
        map.put("l37", l37);
        map.put("l38", l38);
        map.put("l39", l39);
        map.put("l40", l40);
        map.put("l41", l41);
        map.put("l42", l42);
        map.put("l43", l43);
        map.put("l44", l44);
        map.put("l45", l45);
        map.put("l46", l46);
        map.put("l47", l47);
        map.put("l48", l48);
        map.put("l49", l49);
        map.put("l50", l50);
        map.put("l51", l51);
        map.put("l52", l52);
        map.put("l53", l53);
        map.put("l54", l54);
        map.put("l55", l55);
        map.put("l56", l56);
        map.put("l57", l57);
        map.put("l58", l58);
        map.put("l59", l59);
        map.put("l60", l60);
        map.put("l61", l61);
        map.put("l62", l62);
        map.put("l63", l63);
        map.put("l64", l64);
        map.put("l65", l65);
        map.put("l66", l66);
        map.put("l67", l67);
        map.put("l68", l68);
        map.put("l69", l69);
        map.put("l70", l70);
        map.put("l71", l71);
        map.put("l72", l72);
        map.put("l73", l73);
        map.put("l74", l74);
        map.put("l75", l75);
        map.put("l76", l76);
        map.put("l77", l77);
        map.put("l78", l78);
        map.put("l79", l79);
        map.put("l80", l80);
        map.put("l81", l81);
        map.put("l82", l82);
        map.put("l83", l83);
        map.put("l84", l84);
        map.put("l85", l85);
        map.put("l86", l86);
        map.put("l87", l87);
        map.put("l88", l88);
        map.put("l89", l89);
        map.put("l90", l90);        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l24;
    private javax.swing.JLabel l25;
    private javax.swing.JLabel l26;
    private javax.swing.JLabel l27;
    private javax.swing.JLabel l28;
    private javax.swing.JLabel l29;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l30;
    private javax.swing.JLabel l31;
    private javax.swing.JLabel l32;
    private javax.swing.JLabel l33;
    private javax.swing.JLabel l34;
    private javax.swing.JLabel l35;
    private javax.swing.JLabel l36;
    private javax.swing.JLabel l37;
    private javax.swing.JLabel l38;
    private javax.swing.JLabel l39;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l40;
    private javax.swing.JLabel l41;
    private javax.swing.JLabel l42;
    private javax.swing.JLabel l43;
    private javax.swing.JLabel l44;
    private javax.swing.JLabel l45;
    private javax.swing.JLabel l46;
    private javax.swing.JLabel l47;
    private javax.swing.JLabel l48;
    private javax.swing.JLabel l49;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l50;
    private javax.swing.JLabel l51;
    private javax.swing.JLabel l52;
    private javax.swing.JLabel l53;
    private javax.swing.JLabel l54;
    private javax.swing.JLabel l55;
    private javax.swing.JLabel l56;
    private javax.swing.JLabel l57;
    private javax.swing.JLabel l58;
    private javax.swing.JLabel l59;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l60;
    private javax.swing.JLabel l61;
    private javax.swing.JLabel l62;
    private javax.swing.JLabel l63;
    private javax.swing.JLabel l64;
    private javax.swing.JLabel l65;
    private javax.swing.JLabel l66;
    private javax.swing.JLabel l67;
    private javax.swing.JLabel l68;
    private javax.swing.JLabel l69;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l70;
    private javax.swing.JLabel l71;
    private javax.swing.JLabel l72;
    private javax.swing.JLabel l73;
    private javax.swing.JLabel l74;
    private javax.swing.JLabel l75;
    private javax.swing.JLabel l76;
    private javax.swing.JLabel l77;
    private javax.swing.JLabel l78;
    private javax.swing.JLabel l79;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l80;
    private javax.swing.JLabel l81;
    private javax.swing.JLabel l82;
    private javax.swing.JLabel l83;
    private javax.swing.JLabel l84;
    private javax.swing.JLabel l85;
    private javax.swing.JLabel l86;
    private javax.swing.JLabel l87;
    private javax.swing.JLabel l88;
    private javax.swing.JLabel l89;
    private javax.swing.JLabel l9;
    private javax.swing.JLabel l90;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Integer> initSacco() {
        ArrayList<Integer> out = new ArrayList<>();
        for(int i=1; i<=90; i++)
            out.add(i);
        return out;
    }
    
    private void setImage() {
        try {
            Image i =  ImageIO.read(getClass().getResource("/assets/banner.png"));
            ImageIcon icon = new ImageIcon(getScaledIcon(i, jLabel1.getWidth(), jLabel1.getHeight()));
            jLabel1.setIcon(icon);
            jLabel1.setHorizontalAlignment(JLabel.CENTER);
            jLabel1.setVerticalAlignment(JLabel.CENTER);
            jLabel1.setText("");
        } catch (IOException ex) {
            Logger.getLogger(EstrattoDiag.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private Image getScaledIcon(Image i, int x, int y) {
        BufferedImage bi = new BufferedImage(x, y, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = bi.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(i, 0, 0, x, y, null);
        g2.dispose();
        return bi;
    }
}
